//
//  main.swift
//  swim-lake-geneva-api
//
//  Auto Generated by SwiftFunctionsSDK
//
//  Only register/remove Functions. Do Not add other code
//

import AzureFunctions

let registry = FunctionRegistry()

// ****** register/remove your functions. Optionally, set your debug AzureWebJobsStorage and others environment variable ******

//registry.AzureWebJobsStorage = "your debug AzureWebJobsStorage" //Remove before deploying. Do not commit or push any Storage Account keys
//registry.EnvironmentVariables = ["otherStorageConnection": "connectionsString"]

//registry.register(name: "name", function: MyFunction.self)


// ******

AzureFunctionsWorker.shared.main(registry: registry)
